### PR TITLE
Updated docs on setting up services

### PR DESCRIPTION
**Pull request by eXistenZNL**

### CODE REVIEW

**Comment by RickvdStaaij** [comment]
Still need to test this :sweat_smile:

**Comment by eXistenZNL** [comment]
En nu is het moment gekomen om CIMonitor in een container te proppen :)

**Comment by RickvdStaaij** [comment]
@eXistenZNL damn right!

**Comment by RickvdStaaij** [comment]
Merging this! Going to setup another CIMonitor instance soon so then I can fix what's broken

**Pull request merged**
