### PR TITLE
Add small sized toolbar toggle for embedded applications

### LINKED ISSUE #159: Option to hide the toolbar on the bottom
### What

Can we have an option to hide the "toolbar" on the bottom of the page? 

### Why

So that I can embed CIMonitor into an iframe. I'd like to show the last 2-3 builds but the toolbar is a bit "in the way". Might be nice to be able to hide this.

### PR DESCRIPTION
**Pull request by RickvdStaaij**
# What

Create a small size toolbar that can be used in iframes when desired

## Why

Closes #159

## Preview

ci-monitor-toolbar-size

### CODE REVIEW

**Comment by eXistenZNL** [comment]
Codewise it looks really awesome, only thing I am missing is some documentation on how to include it into an iFrame. Make sure to mention mixed content warnings when serving via HTTP. This helps people set it up properly and make the most out of the small toolbar.

**Comment by eXistenZNL** [comment]
One small thing to think about: I miss the color glow on the small toolbar. It could be smaller than the 50px of the normal toolbar but something like 10-20px would still be nice I guess.

**Comment by RickvdStaaij** [comment]
@eXistenZNL brought back the background glow for the small toolbar, plus I've created documentation of embedding the compact mode. Also updated the structure of the docs while I was at it.

**Comment by eXistenZNL** [comment]
Very nice!

**Pull request merged**
